import { useState } from 'react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import { Eye, EyeOff } from 'lucide-react';
import { Brand } from '../components/Brand.jsx'; import { Button } from '../components/Button.jsx'; import { Notice } from '../components/Toast.jsx'; import { useAuth } from '../context/AuthContext.jsx';
export default function AuthPage({ mode, adminOnly = false }) {
  const isRegister = mode === 'register'; const [form, setForm] = useState({ name: '', email: '', password: '' }); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const auth = useAuth(); const navigate = useNavigate();
  if (adminOnly && auth.user?.role === 'admin') return <Navigate to="/admin" replace />;
  if (!adminOnly && auth.user) return <Navigate to={auth.user.role === 'admin' ? '/admin' : '/dashboard'} replace />;
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const data = await (isRegister ? auth.register(form) : auth.login(form)); if (adminOnly && data.user.role !== 'admin') { auth.logout(); throw new Error('This account does not have administrator access'); } navigate(isRegister ? '/dashboard' : data.user.role === 'admin' ? '/admin' : '/dashboard'); } catch (e) { setError(e.message); } finally { setBusy(false); } };
return <main className="auth-page"><Link to="/"><Brand /></Link><section className="auth-card"><div><h1>{adminOnly ? 'Administrator login' : isRegister ? 'Create your account' : 'Welcome back'}</h1><p>{adminOnly ? 'Sign in with an authorized administrator account.' : isRegister ? 'Begin focused SSC typing practice.' : 'Continue your typing preparation.'}</p></div><Notice>{error}</Notice><form onSubmit={submit}>{isRegister && <label>Full name<input required autoComplete="name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Your name" /></label>}<label>Email address<input required type="email" autoComplete="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" /></label><label>Password<div className="auth-password-wrap"><input required minLength="8" type={showPassword ? 'text' : 'password'} autoComplete={isRegister ? 'new-password' : 'current-password'} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="Minimum 8 characters" />
<button className="auth-password-toggle" type="button" aria-label={showPassword ? 'Hide password' : 'Show password'} onClick={() => setShowPassword((v) => !v)}>{showPassword ? <EyeOff size={16} /> : <Eye size={16} />}</button></div></label>{!isRegister && !adminOnly && <Link className="forgot-link" to="/forgot-password">Forgot password?</Link>}<Button disabled={busy}>{busy ? 'Please wait...' : adminOnly ? 'Open admin panel' : isRegister ? 'Create account' : 'Log in'}</Button></form>{!adminOnly && <p className="auth-switch">{isRegister ? 'Already registered?' : 'New to Lexora?'} <Link to={isRegister ? '/login' : '/register'}>{isRegister ? 'Log in' : 'Create an account'}</Link></p>}</section></main>;
}
